Skill:
  blender:
  matasaburo:
  engineer:
  wizard:
  tasogare:
  pharmacy:
  hunter:
  spectator:
  ninja:
  omen:
  knight:

AbilityItems:
  GLOWSTONE_DUST:
  BLAZE_POWDER:
  SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE:
  PURPLE_DYE:
  SMOKER:
  HEART_OF_THE_SEA:
  FEATHER:
  ECHO_SHARD:
  ARCHER_POTTERY_SHERD: