Skill:
  - blender
  - matasaburo
  - engineer
  - wizard
  - tasogare
  - pharmacy
  - hunter
  - spectator
  - ninja
  - omen
  - knight
  - disguise
  - tasogare2

AbilityItems:
  BLAZE_POWDER:
  DUNE_ARMOR_TRIM_SMITHING_TEMPLATE:
  PURPLE_DYE:
  HEART_OF_THE_SEA:
  FEATHER:
  ECHO_SHARD:
  ARCHER_POTTERY_SHERD:
  FIREWORK_STAR:
  COMPASS:
  CARROT_ON_A_STICK:
  WILD_ARMOR_TRIM_SMITHING_TEMPLATE:

EnemyArea:
  1:
    x:
    y:
    z:
    dx:
    dy:
    dz:
  2:
    x:
    y:
    z:
    dx:
    dy:
    dz: